name: 'install-terragrunt'
description: 'Installs Terragrunt'

inputs:
  terragrunt_version:
    description: 'Version of Terragrunt to install'
    required: true
    default: 'latest'
  install_directory:
    description: 'Where to install Terragrunt binary'
    required: true
    default: '${HOME}/.terragrunt'

runs:
  using: "composite"
  steps:
    - run: |
        if [[ "${{ inputs.terragrunt_version }}" == "latest" ]]; then
          terragruntVersion=$( curl --silent https://api.github.com/repos/gruntwork-io/terragrunt/releases/latest | jq -r '.tag_name' )
          echo "Terragrunt Version: ${terragruntVersion}"
        else
          terragruntVersion="${{ inputs.terragrunt_version }}"
          echo "Terragrunt Version: ${terragruntVersion}"
        fi

        mkdir --parents "${{ inputs.install_directory }}"

        pushd "${{ inputs.install_directory }}"

        curl --location https://github.com/gruntwork-io/terragrunt/releases/download/${terragruntVersion}/terragrunt_linux_amd64 \
          --output terragrunt

        chmod +x terragrunt
      shell: bash

    - run:  echo "${{ inputs.install_directory }}" >> ${GITHUB_PATH}
      shell: bash