name: 'install-terraform'
description: 'Installs Terraform'

inputs:
  terraform-version:
    description: 'Version of Terraform to install'
    required: true
    default: 'latest'

runs:
  using: "composite"
  steps:
    - run: |
        if [[ "${{ inputs.terraform-version }}" == "latest" ]]; then
          terraformVersion="${{ inputs.terraform-version }}"
          echo "Terraform Version: ${terraformVersion}"
        else
          terraformVersion="${{ inputs.terraform-version }}"
          echo "Terraform Version: ${terraformVersion}"
        fi  
      shell: bash

    # - run: echo Hello ${{ inputs.who-to-greet }}.
    #   shell: bash
    # - id: random-number-generator
    #   run: echo "::set-output name=random-id::$(echo $RANDOM)"
    #   shell: bash
    # - run: echo "${{ github.action_path }}" >> $GITHUB_PATH
    #   shell: bash          
    # - run: goodbye.sh
    #   shell: bash